# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Parchment mappings (optional, improves parameter names in decompiled sources)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Minecraft / NeoForge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.231
loader_version_range=[1,)

# Mod metadata
mod_id=opencomputers
mod_name=OpenComputers
mod_license=MIT
mod_version=1.8.0-snapshot
mod_group_id=li.cil.oc

# Scala
scala_version=3.4.2
