modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/TheMFCRaft1/OpenComputers-Reworked/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="assets/opencomputers/textures/gui/logo.png"
credits="Inspired by a couple of other mods, most notably ComputerCraft."
authors="Florian 'Sangar' Nuecke, Johannes 'Lord Joda' Lohrer, and all GitHub contributors"
description='''
This mod adds modular computers and robots that can be programmed in Lua.
Ported from Minecraft Forge 1.7.10 to NeoForge 1.21.1.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
